name: beach_app
description: "A new Flutter project."

publish_to:

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5 
  flutter_svg: ^2.0.7
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  carousel_slider: ^5.0.0

dependency_overrides:
  http: ^0.13.5




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  ionicons: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/places/
    - assets/icons/

  uses-material-design: true
  



